### ISSUE TITLE
SW-Indexer should manage the 856 tag generation

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sw-indexer#104]
Move 856 tag generation to indexer so that the tag will be regenerated for updates that might affect the contents of the 856.

in searchworks indexer, if there is a catkey, call the 856 web service

**Comment by blalbrit** [comment]
dor-services 856 method will need to move to PURL

**Comment by blalbrit** [comment]
Lynn's ticket: We also have to figure out how to tie the addition or removal of a catkey with rerunning the release workflow or perhaps just invoking the 856 logic. Perhaps a catkey management blue button?

**Comment by LynnMcRae** [comment]
Original JIRA ticket https://jirasul.stanford.edu/jira/browse/JUMBO-37

**Comment by peetucket** [comment]
Call the marc record service if the object has either a current or previous catkey
