### ISSUE TITLE
856 Symphony processing should only take last entry for a catkey/druid combination

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/sw-indexer#111]
Ticket #104 and pull request #110 are about automating the indexing of changes to catkey based information via the 856 PURL bridge. It means that 856 entries will be generated and passed to Symphony based on changes to the Purl each time it is republished instead of once when it is released. Since changes are accumulated and picked up by Symphony once a night, this increases the chances of a particular catkey/druid combination being represented more than once in the export file on the same day. The current processing does a simple alpha sort of the entire file in order to cast out duplicates, but will retain copies of the same purl entry whose data is different. It will also process a delete before an entry with data, making it appear the delete never happened if a data change should have occurred earlier in the same day.

This is a change to the Symphony process that interprets the 856 PURL file. It will no longer sort the file but simply read the file as is, adding or replacing any catkey/druid combination in the hash it is building up for processing. This means a single 856 purl entry will only be added or replaced or deleted once for any given run based on the final entry in the file. There is no scenario where a particular catkey/druid combination should result in more than one 856/purl action or entry for the given catkey.

**Comment by dlrueda** [comment]
This code is complete and in place.  Using the new code, we successfully processed today's file placed in AFS.  

If additional testing is desired, a test file could be generated and put into place in the test AFS directory, perhaps with multiple lines for same ckey/druid combination, to confirm that only last line is being added (or if last line is a delete line, that 856 on that ckey for that druid is removed).  Please let me know if a file for testing is placed there, we do not have automatic processing on the test directory.

**Comment by LynnMcRae** [comment]
I prod without incident, closing ticket.
