### ISSUE TITLE
verify that release="false" behaves as expected

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sw-indexer#69]
The SW Indexer is not guided by release tags. It will

add/replace a solr doc for a call to /index. If the PURL is not found (e.g., a dark item), it moves on. We cannot assume an error in this case.
delete a solr doc, if present for a call to /delete
an indexer will take these actions for all solr cores it is configured for, typically just one. We have not implemented sub-targeting of cores within an indexer.

**Comment by peetucket** [comment]
connected to sul-dlss/discovery-dispatcher#42

**Comment by mejackreed** [comment]
@blalbrit Can you please provide some canonical examples of release tag data? Currently, discovery-indexer can access release tags, https://github.com/sul-dlss/discovery-indexer/blob/master/lib/discovery-indexer/reader/purlxml_parser_strict.rb#L89-L102

But before I finish implementing I just want to verify that is how we should access them.

**Comment by blalbrit** [comment]
Hi @mejackreed - I set up 8 example objects that I think covers the range of tag options we might see currently: https://consul.stanford.edu/display/GRYPHONDOR/PURL+Fetcher ("Exemplary Objects" at bottom of page). Let me know if those will do, or if you need something else.

**Comment by mejackreed** [comment]
Thanks @blalbrit I had forgotten about that. Anyways. I won't get to finish it but a WIP here: https://github.com/sul-dlss/sw-indexer/pull/83

**Comment by blalbrit** [comment]
Reopening for verification.

**Comment by mejackreed** [comment]
Looking back through this again. I think the pipeline will respect a release tag (at purl-fetcher) but sw-indexer (and base-indexer) removed that functionality.

Need a better understanding here. Should sw-indexer (or base-indexer) always respect a release tag?
