### ISSUE TITLE
Create/deploy SW Preview indexer

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sw-indexer#72]
analysis whether or not separate indexer needed for Preview

**Comment by lmcglohon** [comment]
Instead of having the sw-mapper do the checking of valid data for indexing, push the determination of valid metadata into the item-releaseWF that prevents release to SW Production if not enough is available. For SW Preview, we only want to require the title.

**Comment by lmcglohon** [comment]
SW indexer will not do data validation so it is target agnostic.
