### ISSUE TITLE
Make sure all indexer target names in configs are upcased.

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sw-indexer#77]

**Comment by drh-stanford** [comment]
Does this imply that release tags need to be ALL CAPS when used in the PURL fetcher API?

**Comment by mejackreed** [comment]
No. The assumption is that data is dirty and we can't control it.

**Comment by peetucket** [comment]
checked and updated all existing targets in sw-indexing-dev, -stage and -prod, and revs-indexing-dev, -stage and -prod
