### ISSUE TITLE
Add monitoring endpoint

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sw-indexer#87]
We need a `/status` endpoint that uses `OkComputer` to monitor the state of the application.

What should we be monitoring? Solr connections?

**Comment by drh-stanford** [comment]
This has to be done at the base_indexer level first.

**Comment by drh-stanford** [comment]
Having a problem getting the Rails engine routing to work :(. The OkComputer mounts are not working. Needs more debugging...

![screen shot 2016-08-25 at 1 36 01 pm](https://cloud.githubusercontent.com/assets/1861171/17985061/f98ef958-6ac8-11e6-8349-50f30cf0a488.png)

**Comment by drh-stanford** [comment]
It put in a PR for this to base_indexer but it has a hack that we should probably find the correct solution for...

**Comment by drh-stanford** [comment]
suggestion is to move the monitoring bits out of base_indexer and into sw_indexer app itself.

**Comment by lmcglohon** [comment]
Add checks for solr targets

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/base_indexer/issues/47

**Comment by drh-stanford** [comment]
I have a branch for this, but I'm not able to get my laptop configured correctly to test it. Will test in -dev...

**Comment by drh-stanford** [comment]
Removed `is_it_working-cbeer` from base_indexer (see https://github.com/sul-dlss/base_indexer/pull/49) and added PR #97 to add OkComputer checks to sw-indexer.

**Comment by drh-stanford** [comment]
The default solr URL in the configuration yields 404 errors so the `targets` monitoring endpoint fails. We need to look into using a Solr "ping" route.
