### ISSUE TITLE
Review to see if we autocommits are needed in solrconfig

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sw-indexer#91]
The solrconfig for the solr targets of the sw-indexer (and revs indexer) may need to be adjusted to allow for autocommits to occur at a more frequent level.  Since a single document delete operation (e.g. when doing a release=false) may occur separately from other updates and possibly infrequently, the document may not be removed from solr until a commit occurs.  The current base_indexer does not issue a commit after each operation (nor do I believe should it).

**Comment by drh-stanford** [comment]
You can add a `commit=true` to the end of the URL when you execute a Solr update, but `RSolr` does not support this behavior. So, you either need to send a `commit` message explicitly, or rely on the auto commit behavior in the Solr core's configuration. I'd look into issuing an explicit commit message after every delete.

**Comment by mejackreed** [comment]
When working on #105, I noticed that deletes were not committing automatically. Not sure if we care about this again but just thought I would raise it.

**Comment by peetucket** [comment]
I noticed when I was confirming release=false behavior that the deletes were eventually committed, just not immediately.  I didn't pin down the exact timeframe, but it might have been as high as 30 minutes.  If I issued a commit manually, the docs vanished.
